# Generated by Django 4.0.2 on 2022-04-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(max_length=50, unique=True)),
                ('hostelCity', models.CharField(max_length=50)),
                ('hostelStreet', models.CharField(max_length=50)),
                ('hostelType', models.CharField(max_length=50)),
                ('hostelPhone', models.CharField(default='00000000', max_length=50)),
                ('hostelTotalRooms', models.CharField(max_length=100)),
                ('hostelPhoto', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('userFName', models.CharField(max_length=50)),
                ('userLName', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=50)),
                ('userAddress', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=100)),
                ('userPhoto', models.ImageField(default='defaultProfie.jpg', null=True, upload_to='')),
                ('totalHostels', models.CharField(max_length=100, null=True)),
                ('ownerLicense', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(max_length=50, unique=True)),
                ('hostelCity', models.CharField(max_length=50)),
                ('hostelStreet', models.CharField(max_length=50)),
                ('hostelType', models.CharField(max_length=50)),
                ('hostelPhoto', models.ImageField(null=True, upload_to='')),
                ('hostelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hostel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostelOwnerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='BookedHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('hostelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hostel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
