# Generated by Django 4.0.2 on 2022-04-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_savedhostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(max_length=50, unique=True)),
                ('hostelCity', models.CharField(max_length=50)),
                ('hostelStreet', models.CharField(max_length=50)),
                ('hostelType', models.CharField(max_length=50)),
                ('hostelPhoto', models.ImageField(null=True, upload_to='')),
                ('hostelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hostel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
