# Generated by Django 4.0.2 on 2022-04-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_savedhostel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedHostel',
        ),
    ]
