# Generated by Django 4.0.2 on 2022-04-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_savedhostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedhostel',
            name='hostelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='users.hostel'),
        ),
        migrations.AlterField(
            model_name='savedhostel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user'),
        ),
    ]
