# Generated by Django 4.0.2 on 2022-04-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_savedhostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(max_length=50, unique=True)),
                ('hostelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='users.hostel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user')),
            ],
        ),
    ]
