# Generated by Django 4.0.2 on 2022-04-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_savedhostel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedHostel',
        ),
    ]
