# Generated by Django 4.0.2 on 2022-04-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_savedhostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelName',
        ),
    ]
