# Generated by Django 4.0.2 on 2022-04-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_savedhostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelCity',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelName',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelPhone',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelPhoto',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelStreet',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelType',
        ),
    ]
