# Generated by Django 4.0.2 on 2022-04-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_savedhostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelCity',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelName',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelPhone',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelPhoto',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelStreet',
        ),
        migrations.RemoveField(
            model_name='savedhostel',
            name='hostelType',
        ),
        migrations.AlterField(
            model_name='savedhostel',
            name='hostelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='users.hostel'),
        ),
        migrations.AlterField(
            model_name='savedhostel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user'),
        ),
    ]
