# Generated by Django 4.0.2 on 2022-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_savedhostel_hostelcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedhostel',
            name='hostelID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='savedhostel',
            name='userID',
            field=models.CharField(max_length=50),
        ),
    ]
