# Generated by Django 4.0.2 on 2022-04-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_savedhostel_hostelid_alter_savedhostel_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedHostel',
        ),
    ]
