# Generated by Django 4.0.2 on 2022-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_delete_bookedhostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelID', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('roomID', models.CharField(max_length=50)),
            ],
        ),
    ]
