# Generated by Django 4.0.2 on 2022-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_bookedhostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedhostel',
            name='bookingDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
