# Generated by Django 4.0.2 on 2022-04-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_bookedhostel_bookingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(max_length=50, unique=True)),
                ('roomPrice', models.CharField(max_length=50)),
            ],
        ),
    ]
