# Generated by Django 4.0.2 on 2022-04-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedHostel',
        ),
    ]
