# Generated by Django 4.0.2 on 2022-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_delete_bookedhostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelID', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
                ('bookingDate', models.DateField()),
                ('roomID', models.CharField(max_length=50)),
                ('roomType', models.CharField(max_length=50)),
            ],
        ),
    ]
