# Generated by Django 4.0.2 on 2022-04-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_bookedhostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ownerLicense',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalHostels',
        ),
    ]
