# Generated by Django 4.0.2 on 2022-04-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_user_ownerlicense_remove_user_totalhostels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelID', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
            ],
        ),
    ]
