# Generated by Django 4.0.2 on 2022-04-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_rename_registerhostel_registeredhostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='hostelOwnerID',
        ),
    ]
