# Generated by Django 4.0.2 on 2022-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50)),
                ('hostelID', models.CharField(max_length=50)),
                ('notificationMessage', models.CharField(max_length=200)),
                ('notificationDate', models.DateTimeField()),
            ],
        ),
    ]
