# Generated by Django 4.0.2 on 2022-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_usernotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userAddress',
            new_name='userCity',
        ),
        migrations.AddField(
            model_name='user',
            name='userStreet',
            field=models.CharField(default='jwagal', max_length=100),
        ),
    ]
