# Generated by Django 4.0.2 on 2022-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_useraddress_user_usercity_user_userstreet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenityName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelID', models.CharField(max_length=50)),
                ('amenityID', models.CharField(max_length=50)),
            ],
        ),
    ]
